Update bootstrap, setup, and Brewfile to work on Linux systems

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -7,25 +7,38 @@ set -e
 
 cd "$(dirname "$0")/.."
 
-if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ]; then
+fancy_echo() {
+  local fmt="$1"; shift
+
+  # shellcheck disable=SC2059
+  printf "\\n$fmt\\n" "$@"
+}
+
+if [ -f "Brewfile" ]; then
+  if ! $(which brew 2>&1 >/dev/null); then
+    echo "ERROR: We couldn't find homebrew! It is needed to continue"
+    echo "       Please install using instructions from https://brew.sh/ and retry."
+    exit 1
+  fi
+
   brew bundle check >/dev/null 2>&1  || {
-    echo "==> Installing Homebrew dependencies…"
+    fancy_echo "==> Installing Homebrew dependencies…"
     brew bundle
   }
 fi
 
-if [ -f ".ruby-version" ] && [ -z "$(rbenv version-name 2>/dev/null)" ]; then
-  echo "==> Installing Ruby…"
-  rbenv install --skip-existing
-  which bundle >/dev/null 2>&1  || {
-    gem install bundler
-    rbenv rehash
-  }
-fi
+#if [ -f ".ruby-version" ] && [ -z "$(rbenv version-name 2>/dev/null)" ]; then
+#  echo "==> Installing Ruby…"
+#  rbenv install --skip-existing
+#  which bundle >/dev/null 2>&1  || {
+#    gem install bundler
+#    rbenv rehash
+#  }
+#fi
 
-if [ -f "Gemfile" ]; then
-  echo "==> Installing gem dependencies…"
-  bundle check --path vendor/gems >/dev/null 2>&1  || {
-    bundle install --path vendor/gems --quiet --without production
-  }
-fi
+#if [ -f "Gemfile" ]; then
+#  echo "==> Installing gem dependencies…"
+#  bundle check --path vendor/gems >/dev/null 2>&1  || {
+#    bundle install --path vendor/gems --quiet --without production
+#  }
+#fi
